// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sillypub;

namespace sillypub.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210605085259_CreateReviewSchema")]
    partial class CreateReviewSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("sillypub.Models.Review", b => {
                b.Property<string>("Id")
                    .HasColumnType("TEXT");
                b.Property<int>("Rating")
                    .HasColumnType("INTEGER");
                b.Property<string>("Name")
                    .HasColumnType("TEXT");
                b.Property<string>("Content")
                    .HasColumnType("TEXT");
                b.Property<int>("PhoneNumber")
                    .HasColumnType("INTEGER");
                b.HasOne("sillypub.Models.User", null)
                    .WithOne()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.ToTable("Review");
            });
#pragma warning restore 612, 618
        }
    }
}
